/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Thu Jan  9 15:05:48 KST 2014
 * 
 */

/* Generation options: */
#ifndef __mkTest_h__
#define __mkTest_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkIMemory.h"

namespace bluesim
{
  
  /* Class declaration for the mkTest module */
  class MOD_mkTest : public Module {
   
   /* Clock handles */
   private:
    tClock __clk_handle_0;
   
   /* Instantiation parameters */
   public:
   
   /* Module state */
   public:
    MOD_mkIMemory INST_iMem;
    MOD_Reg<tUInt32> INST_pc;
   
   /* Constructor */
   public:
    MOD_mkTest(char const *name, Module *parent);
   
   /* Symbol init methods */
   private:
    void init_symbols_0();
   
   /* Reset signal definitions */
   private:
    tUInt8 PORT_RST_N;
   
   /* Port definitions */
   public:
   
   /* Publicly accessible definitions */
   public:
    tUInt32 DEF_x__h557;
   
   /* Local definitions */
   private:
   
   /* Rules */
   public:
    void RL_run();
    void RL_finish();
   
   /* Methods */
   public:
   
   /* Reset routines */
   public:
    void reset_RST_N(tUInt8 ARG_rst_in);
   
   /* Static handles to reset routines */
   public:
   
   /* Pointers to reset fns in parent module for asserting output resets */
   private:
   
   /* Functions for the parent module to register its reset fns */
   public:
   
   /* Functions to set the elaborated clock id */
   public:
    void set_clk_0(char const *s);
   
   /* State dumping routine */
   public:
    void dump_state(unsigned int indent);
   
   /* VCD dumping routines */
   public:
    unsigned int dump_VCD_defs(unsigned int levels);
    void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTest &backing);
    void vcd_defs(tVCDDumpType dt, MOD_mkTest &backing);
    void vcd_prims(tVCDDumpType dt, MOD_mkTest &backing);
    void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTest &backing);
  };
}

#endif /* ifndef __mkTest_h__ */
