/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Thu Jan  9 15:05:48 KST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "schedule.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"

#include "mkTest.h"

namespace bluesim
{
  
  /* Top-level module instances */
  static MOD_mkTest *mkTest_instance = NULL;
  
  
  /* Schedule functions */
  
  void schedule_posedge_CLK()
  {
    MOD_mkTest &INST_top = *mkTest_instance;
    tUInt8 DEF_INST_top_DEF_pc_ULT_100___d2;
    tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_run;
    tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_run;
    tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_finish;
    tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_finish;
    INST_top.DEF_x__h557 = INST_top.INST_pc.METH_read();
    DEF_INST_top_DEF_pc_ULT_100___d2 = (INST_top.DEF_x__h557) < 100u;
    DEF_INST_top_DEF_CAN_FIRE_RL_finish = !DEF_INST_top_DEF_pc_ULT_100___d2;
    DEF_INST_top_DEF_WILL_FIRE_RL_finish = DEF_INST_top_DEF_CAN_FIRE_RL_finish;
    DEF_INST_top_DEF_CAN_FIRE_RL_run = DEF_INST_top_DEF_pc_ULT_100___d2;
    DEF_INST_top_DEF_WILL_FIRE_RL_run = DEF_INST_top_DEF_CAN_FIRE_RL_run;
    if (DEF_INST_top_DEF_WILL_FIRE_RL_finish)
      INST_top.RL_finish();
    if (DEF_INST_top_DEF_WILL_FIRE_RL_run)
      INST_top.RL_run();
    if (do_reset_ticks())
    {
      INST_top.INST_pc.rst_tick__clk__1((tUInt8)1u);
    }
  }
  
  /* Model creation/destruction functions */
  
  void create_model(bool master)
  {
    init_reset_request_counters();
    mkTest_instance = new MOD_mkTest("top", NULL);
    bk_get_or_define_clock("CLK");
    if (master)
    {
      bk_alter_clock(bk_get_clock_by_name("CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
      bk_use_default_reset();
    }
    bk_set_clock_event_fn(bk_get_clock_by_name("CLK"),
			  schedule_posedge_CLK,
			  NULL,
			  (tEdgeDirection)(POSEDGE));
    (mkTest_instance->INST_iMem.set_clk_0)("CLK");
    (mkTest_instance->set_clk_0)("CLK");
  }
  void destroy_model()
  {
    delete mkTest_instance;
    mkTest_instance = NULL;
  }
  void reset_model(bool asserted)
  {
    (mkTest_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
  }
  void * get_instance()
  {
    return mkTest_instance;
  }
  
  /* Fill in version numbers */
  void get_version(unsigned int *year,
		   unsigned int *month,
		   char const **annotation,
		   char const **build)
  {
    *year = 2011u;
    *month = 6u;
    *annotation = "D";
    *build = "24470";
  }
  
  /* Get the model creation time */
  time_t get_creation_time()
  {
    
    /* Thu Jan  9 06:05:48 UTC 2014 */
    return 1389247548llu;
  }
  
  /* Control run-time licensing */
  tUInt64 skip_license_check()
  {
    return 0llu;
  }
  
  /* State dumping function */
  void dump_state()
  {
    (mkTest_instance->dump_state)(0u);
  }
  
  /* VCD dumping functions */
  MOD_mkTest & mkTest_backing()
  {
    static MOD_mkTest *instance = NULL;
    if (instance == NULL)
    {
      vcd_set_backing_instance(true);
      instance = new MOD_mkTest("top", NULL);
      vcd_set_backing_instance(false);
    }
    return *instance;
  }
  void dump_VCD_defs()
  {
    (mkTest_instance->dump_VCD_defs)(vcd_depth);
  }
  void dump_VCD(tVCDDumpType dt)
  {
    (mkTest_instance->dump_VCD)(dt, vcd_depth, mkTest_backing());
  }
}
